#!/bin/sh

### BEGIN INIT INFO
# Provides:          exec-by-mail
# Required-Start:    $network
# Required-Stop:
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: exec-by-mail
# Description:       execute commands by e-mail
### END INIT INFO

. /lib/lsb/init-functions

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=exec-by-mail
PROGRAM=/usr/bin/exec-by-mail
CONF=/etc/exec-by-mail.conf


test -x $PROGRAM || exit 0

case "$1" in
  start)
    log_begin_msg "Starting exec-by-mail"
    $PROGRAM --start -f $CONF
    log_end_msg 0
    ;;
  stop)
    $PROGRAM --stop -f $CONF
    ;;
  force-reload|restart)
    $PROGRAM --stop -f $CONF 
    $PROGRAM --start -f $CONF
    ;;
  status)
    if [ -s /var/run/$NAME.pid ]; then
      RUNNING=$(cat /var/run/$NAME.pid)
      if [ -d /proc/$RUNNING ]; then
        #if [ $(readlink /proc/$RUNNING/exe) = $PROGRAM ]; then
        TEST=$(cat /proc/$RUNNING/cmdline|grep $PROGRAM|wc -l)
        if [ $TEST != 0 ]; then
          echo "$NAME is running."
          exit 0
        fi
      fi

      # No such PID, or executables don't match
      echo "$NAME is not running, but pidfile existed."
      #rm /var/run/$NAME.pid
      exit 1
    else
      #rm -f /var/run/$NAME.pid
      echo "$NAME not running."
      exit 1
    fi
    ;;
  *)
    log_success_msg "Usage: $PROGRAM {start|stop|restart|force-reload|status}"
    exit 1
esac

exit 0
